version: "3"
services:
  api-server:
    build:
      context: .
      dockerfile: ./docker/api-server/Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
  db-server:
    image: postgres:11
    volumes:
      - ./db-target:/var/lib/postgresql/data
    ports:
      - "5432:5432"