version: "3"
services:
  api-server:
    build:
      context: .
      dockerfile: ./docker/api-server/Dockerfile
    ports:
      - "8080:8080"
  db-server:
    build:
      context: .
      dockerfile: ./docker/db-server/Dockerfile
    ports:
      - "5432:5432"