version: "3.5"
services:
  api-server:
    image: mondial-api
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - mondial
    ports:
      - "8080:8080"
      - "8000:8000"
networks:
  mondial:
    name: mondial
